# Generated by Django 3.0.8 on 2020-08-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='content_loc',
            field=models.CharField(default='home', max_length=100),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='image_loc',
            field=models.ImageField(default='/', upload_to=''),
        ),
    ]
