# Generated by Django 3.0.8 on 2020-08-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200806_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteContent',
        ),
    ]
