# Generated by Django 3.0.8 on 2020-08-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_sitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('main_text', models.CharField(max_length=1000)),
                ('image_loc', models.ImageField(default='/', upload_to='')),
                ('content_loc', models.CharField(default='home', max_length=100)),
            ],
        ),
    ]
