# Generated by Django 3.0.8 on 2020-08-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sitecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='content_loc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='image_loc',
            field=models.ImageField(upload_to=''),
        ),
    ]
