# Generated by Django 3.0.8 on 2020-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200806_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='image_loc',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='main_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='title_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
