# Generated by Django 3.0.8 on 2020-08-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200806_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='image_loc',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
