# Generated by Django 3.0.8 on 2020-08-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200807_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(blank=True, max_length=100)),
                ('main_text', models.CharField(blank=True, max_length=1000)),
                ('content_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteContent',
        ),
    ]
