# Generated by Django 3.0.8 on 2020-08-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200825_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(blank=True, max_length=100)),
                ('main_text', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(blank=True, max_length=100)),
                ('main_text', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FeatureContent',
        ),
    ]
