# Generated by Django 3.0.8 on 2021-05-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210512_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselcontent',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
