# Generated by Django 3.0.8 on 2021-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210512_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselcontent',
            name='button_text',
            field=models.CharField(default='Click Here', max_length=50),
        ),
        migrations.AddField(
            model_name='carouselcontent',
            name='link',
            field=models.CharField(default='/', max_length=50),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='button_text',
            field=models.CharField(default='Click Here', max_length=50),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='link',
            field=models.CharField(default='/', max_length=50),
        ),
        migrations.AlterField(
            model_name='carouselcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
