# Generated by Django 3.0.8 on 2021-05-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certify', '0002_certifyheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifycontent',
            name='main_text',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='certifycontent',
            name='subtitle_text',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='certifyheader',
            name='main_text',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='certifyheader',
            name='subtitle_text',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
