# Generated by Django 3.0.8 on 2020-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200825_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='content_loc',
            field=models.CharField(default='blank', max_length=100),
        ),
    ]
