# Generated by Django 3.0.8 on 2021-05-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210512_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(blank=True, max_length=100)),
                ('main_text', models.CharField(blank=True, max_length=2000)),
                ('subtitle_text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
