# Generated by Django 3.0.8 on 2021-05-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210512_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='certcontent',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
