# Generated by Django 3.0.8 on 2021-05-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_certcontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ButtonContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(default='Click Me', max_length=50)),
                ('load_file', models.FileField(upload_to='')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductContent')),
            ],
        ),
    ]
