# Generated by Django 3.0.8 on 2021-05-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210512_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
